language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kunjan1610/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kunjan1610/docker-react npm run test